version: 0.0
os: linux

files:
  - source: index.html
    destination: /var/www/html/
  - source: config/httpd.conf
    destination: /etc/httpd/conf/httpd.conf
    owner: apache
    group: apache
    mode: 0644
    
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
